version: '3'

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/var/www/html"
    ports:
      - 8181:80
    depends_on:
      - db
    command: apache2-foreground

  db:
    image: "mysql:latest"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: secureauction
      MYSQL_USER: appuser    
      MYSQL_PASSWORD: secure_password    
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 8001:80
      environment:
        - PMA_HOST=db
        - PMA_PORT=3306