# Set the Docker Compose file version
version: '3.8'

# Define the services that make up the application stack
services:
  # Define the web service, which represents the PHP web application
  web:
    # Build the Docker image using the provided Dockerfile
    build: .
    # Map the host's port 8000 to the container's port 80
    ports:
      - "8000:80"
    # Define a dependency on the db service, ensuring it starts before the web service
    depends_on:
      - db

  # Define the db service, which represents the MySQL database
  db:
    # Use the official MySQL 5.7 image as the base image
    image: "mysql:5.7"
    # Set environment variables used by the MySQL image for configuration
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: secureauction
      MYSQL_USER: secureauction
      MYSQL_PASSWORD: secureauction
