version: '3'

services:
  www:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./public:/var/www/html"
    ports:
      - 8181:80
    depends_on:
      - db
    command: apache2-foreground

  db:
    image: "mysql:latest"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: secureauction
      MYSQL_USER: appuser    
      MYSQL_PASSWORD: secure_password    
